### ISSUE TITLE
Mr. B, I am having issues with BS4

### ISSUE THREAD

**Issue by janelle-c** [Janelle-Steven-Semantics/janellestevenadvcsproject#15]
beautifulsoup4 does not work with my python. I tried a lot of things like the good ol install/ uninstall. I am trying to convert the code to Python 3, what I am running on, and nothing is working. Help thanks.

**Comment by battis** [comment]
Looks like it was a combo issue of getting a virtual environment created in your repository and then pointing PyCharm's interpreter at it.
